"""add api response

Revision ID: 9b3a1c35c47c
Revises: 9f01c24119cf
Create Date: 2026-09-16 10:40:15.583419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3a1c35c47c'
down_revision: Union[str, Sequence[str], None] = '9f01c24119cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apis', sa.Column('response', sa.Text(), nullable=False))
    op.drop_column('apis', 'reponse')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apis', sa.Column('reponse', sa.TEXT(), nullable=False))
    op.drop_column('apis', 'response')
    # ### end Alembic commands ###
