"""tables update

Revision ID: 9f01c24119cf
Revises: 15c9722b94fb
Create Date: 2026-09-13 15:31:20.449847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f01c24119cf'
down_revision: Union[str, Sequence[str], None] = '15c9722b94fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apis', sa.Column('supported_formats', sa.JSON(), nullable=False))
    op.add_column('apis', sa.Column('end_point', sa.Text(), nullable=False))
    op.add_column('apis', sa.Column('method', sa.Text(), nullable=False))
    op.add_column('apis', sa.Column('reponse', sa.Text(), nullable=False))
    op.add_column('apis', sa.Column('auth_method', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apis', 'auth_method')
    op.drop_column('apis', 'reponse')
    op.drop_column('apis', 'method')
    op.drop_column('apis', 'end_point')
    op.drop_column('apis', 'supported_formats')
    # ### end Alembic commands ###
